### ISSUE TITLE
Image function of BigBrainVolume expects bounding box to be in voxel space

### ISSUE THREAD

**Issue by marcenko** [FZJ-INM1-BDA/siibra-python#10]
If passing a bounding box to the `clip `argument to the `Image `function of `BigBrainVolume`, it expects the bounding box to be specified in voxel space of the specified resolution, which is highly inconvenient for users.
The bounding box should be defined in millimeter space and the class should do the conversion itself (which it can do using it's affine matrix).

**Comment by dickscheid** [comment]
Fixed in v0.1a4 which introduced to have all non-protected method arguments in mm space, and proper volume-of-interest specifications.
