### ISSUE TITLE
[feature request] support VOI spatial feature

### ISSUE THREAD

**Issue by xgui3783** [FZJ-INM1-BDA/siibra-python#118]
e.g. PLI volume of interest

**Comment by dickscheid** [comment]
This is already implemented! 

```python
import siibra
atlas = siibra.atlases.MULTILEVEL_HUMAN_ATLAS
hip = atlas.get_region("hippocampal")
vois = siibra.get_features(hip, siibra.modalities.VolumeOfInterest)
assert(len(vois)>0)
print(vois[0].name)
print(vois[0].volumes)
```


However, I just discovered that it wasn't functional in the latest version. A fix has just been implemented (3b114eeb) and will be released as 0.3a4 now.

**Comment by dickscheid** [comment]
Of course, the number fo VOIs is still small. Curation team is working to provide more.

**Comment by dickscheid** [comment]
@xgui3783 can you try and close this issue if it works?
