### ISSUE TITLE
Add coordinate assignment across all known parcellations

### ISSUE THREAD

**Issue by xgui3783** [FZJ-INM1-BDA/siibra-python#119]
This came from a user of siibra-python. I am interpreting his expectation:

Given point x,y,z, show related parcellation (name, other property, etc)

I understand for JulichBrain it is already possible, but support for other parcellations (BA, AAL?) would be nice.

request as below:

> Easier accessibility/visibility of "standard" labelling schemes (especially Brodmann areas) and automatic display of label at current cross-hair. Is it feasible to include a BA atlas and the AAL? Or, rather more demanding, to have an adaptive parcellation scheme such that one may choose large macroanatomical labels and then drill down to smaller scale ones using a button/menu available at all times on screen?

**Comment by dickscheid** [comment]
The functionality of assigning areas to coordinates does not depend on the parcellations, it works for any parcellation map. Julich-Brain is simply the default if you get a map from the atlas. However, AAL and Brodman are not yet included as parcellations. AAL should be easy and will be added soon, for Brodmann I would need to find a volumetric parcellation that we could integrate.

**Comment by xgui3783** [comment]
should already been possible? pending close

**Comment by AhmetNSimsek** [comment]
> should already been possible? pending close

I think so too. I will run a test and close it.
