### ISSUE TITLE
[bug regression] siibra-python 0.3a4 region.supported_spaces are extremely memory hungry

### ISSUE THREAD

**Issue by xgui3783** [FZJ-INM1-BDA/siibra-python#137]
This results in a massive degredation of siibra-api's stability, resulting in constant pod crashes (due to OOM, I can assume)

possibily related to #106

**Comment by xgui3783** [comment]
some statistic:

0.3a4: 3 replicas resulted in 6 restarts in 30 minute, 1 user (staging)
pre-0.3a4: 3 replicas, 2 restart in 6 days, 100's users

**Comment by dickscheid** [comment]
@xgui3783 this should be fixed now by 3ae8a2673901d2d231e7be6514c517d0bd38b4be and cdfa626798c97f71d9f38a6699fb41c4cacd8716. I will build a new package that you can test.

**Comment by dickscheid** [comment]
@xgui3783 Could you verify that the problem is solved in v0.3a5?

**Comment by xgui3783** [comment]
I have not yet have a chance to look at if the issue can/has been resolved, but we can close this issue. We can always reopen when/if I noticed the issue remains unresolved.
