### ISSUE TITLE
[bug] check validity for rat receptor data

### ISSUE THREAD

**Issue by xgui3783** [FZJ-INM1-BDA/siibra-python#141]
receptor datasets such as https://search.kg.ebrains.eu/instances/Dataset/19cc79ac-fecd-4576-90e3-e7cabd42fe9f are fetched by siibra-python. 

need to double check that it is being parsed correctly. in explorer, it looks  a bit weird (profile doesn't work at all):
![Screenshot from 2021-11-30 12-14-27](https://user-images.githubusercontent.com/19381783/144037521-10b2fe54-6c8a-4fa7-b391-392fd81f17b1.png)

**Comment by dickscheid** [comment]
I assume that the format of the receptor datasets in rat brains is not 100% identical, since it had not been standardizd for curation. It might be more sustainable to define a standard now and consider an update of the datasets, isntead of dealing with several formats in the code.

**Comment by AhmetNSimsek** [comment]
Is this still an issue?

**Comment by xgui3783** [comment]
since v0.4 this should no longer be an issue, since the receptor features are now more manually curated.
