### ISSUE TITLE
[enhancement] siibra should have more actionable error messages when ebrains token not set

### ISSUE THREAD

**Issue by xgui3783** [FZJ-INM1-BDA/siibra-python#146]
as of 0.3a5

if ebrains token is not set, the error is cryptic and not actionable

expected:

clear, actionable steps to move forward

1. go to ebrains.eu -> get account
2. go to kg.ebrains.eu -> request API access
3. go to nexus-int.hbp.org/oauth, login, copy the token
4. either
4a. set token via env var `export HBP_AUTH_TOKEN={PASTE TOKEN HERE}`
4b. set token in python `siibra.set_ebrains_token("{PASTE TOKEN HERE}")`

bonus:
- check if stack trace can be muted

**Comment by AhmetNSimsek** [comment]
Was fixed with https://github.com/FZJ-INM1-BDA/siibra-python/commit/9e0d24b7dd5f1953cc557ea160184434d43fb497
