### ISSUE TITLE
import siibra fails when jugit is down

### ISSUE THREAD

**Issue by i-Zaak** [FZJ-INM1-BDA/siibra-python#152]
Hi, seems like the import of the siibra package depends on the availability of the jugit server:

```python
>>> import siibra
[siibra:INFO] Version: 0.3a11
[siibra:WARNING] This is a development release. Use at your own risk.
[siibra:INFO] Please file bugs and issues at https://github.com/FZJ-INM1-BDA/siibra-python.
[siibra:ERROR] Cannot connect to configuration server GitlabConnector https://jugit.fz-juelich.de/api/v4/projects/3484/repository siibra-0.3a11, trying a different mirror
HTTPSConnectionPool(host='jugit.fz-juelich.de', port=443): Max retries exceeded with url: /api/v4/projects/3484/repository/tree?ref=siibra-0.3a11&path=spaces&per_page=100&page=1&recursive=False (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f60db273fd0>: Failed to establish a new connection: [Errno 113] No route to host'))
```

[traceback.txt](https://github.com/FZJ-INM1-BDA/siibra-python/files/7920065/traceback.txt)

**Comment by dickscheid** [comment]
This is the case when first loading the package. siibra will then retrieve atlas configurations from the server, that we do want to maintain separately. The configurations are afterwards cached, so this happens only once per version update except you explicitely request different configuration verssions.

The uptime of the server should be good, and there is a mirror that is used if the server is down. Therefore the above should be very unlikely. We will check why no mirror could be reached.

**Comment by xgui3783** [comment]
this is rather strange. we setup a mirror at gitlab.ebrains.eu for this exactly purpose. 

@dickscheid I can take a look at this issue? (I believe I was the one who setup the mirror in the first place)
