### ISSUE TITLE
[bug/enh] connectivity feature query result in the download of >400mb file, with no progress indicator

### ISSUE THREAD

**Issue by xgui3783** [FZJ-INM1-BDA/siibra-python#190]
as of [2dbd8aa](https://github.com/FZJ-INM1-BDA/siibra-python/commit/2dbd8aae9e6d0a08d3fa2155f18bdd02b830907c)

to reproduce:

```python
import siibra

p = siibra.parcellations['2.9']
features = siibra.get_features(p, 'connectivity')
```

Then, kernel seems to be stuck at
```
Found 2 versions for dataset 'Parcellation-based structural and resting-state functional brain connectomes of a healthy cohort' (v1.0, v1.1). Will use v1.1 per default.
```

In the background, it's trying to download <hbp-d000059_Atlas_based_HCP_connectomes_v1.1_pub/294-Julich-Brain.zip>, but since it's >400mb, it does not finish for a while. With no progress bar/warning, this can be misidentified as a bug.

**Comment by AhmetNSimsek** [comment]
Was solved with fab99392286c3f4ebc3edc9ae44e89d541dffa09
