### ISSUE TITLE
Refactor data features in siibra-python

### ISSUE THREAD

**Issue by dickscheid** [FZJ-INM1-BDA/siibra-python#194]
- [ ] new tabular data feature hierarchy for profiles and fingerprints, providing reusable descriptions of default plots in a visualization grammar like vega
- [ ] new data feature for object locations / dsitrbutions, like detected cell bodies, as clouds of spatial objects (see https://github.com/FZJ-INM1-BDA/siibra/issues/52)
- [x] new feature type for 2D sections
- [x] new feature type for 3D volumes, combined with the current VOIs (see also https://github.com/FZJ-INM1-BDA/siibra/issues/60)
  - [ ] ingest prerelease data to data-vm 
  - [ ] release metadata to dataproxy
  - [ ] refactor connect the voi feature query -> if token is set, attempt to fetch controlled 
  - [ ] user access control of the metadata dataproxy bucket (add users)
- [ ] new feature type for physiology, using HDG, replacing IEEG feature implementations

**Comment by xgui3783** [comment]
Would the WIP data template but a sub goal or a sibling goal to refactor of data features?

I noticed that the data template, despite us recognising it to be important and urgent, does not have its own issue/card.

**Comment by AhmetNSimsek** [comment]
This issue will be divided into pieces for easier tracking.
