### ISSUE TITLE
Structural connectivity query fails

### ISSUE THREAD

**Issue by dickscheid** [FZJ-INM1-BDA/siibra-python#199]
When requesting StreamlineCounts, the dataset query seems not to work any more:

```python
import siibra
assert siibra.__version__ == '0.3a17'
julich_brain = siibra.parcellations.JULICH_BRAIN_CYTOARCHITECTONIC_MAPS_2_9
siibra.set_ebrains_token("<a valid api token>")
siibra.get_features(julich_brain, siibra.modalities.StreamlineCounts)
```

Expected: A list of connectivity matrix features

Actual result: No features, with warning:

```
[siibra:ERROR] EBRAINS knowledge graph query for dataset 0f1ccc4a-9a11-4697-b43f-9c9c8ac543e6 did not return any files. It seems that your EBRAINS authentication does not provide sufficient privileges to access the connectivity data.
[siibra:ERROR] The file 294-Julich-Brain.zip requested from EBRAINS dataset 0f1ccc4a-9a11-4697-b43f-9c9c8ac543e6 is not available in this repository.
[siibra:ERROR] The file 096-HarvardOxfordMaxProbThr0.zip requested from EBRAINS dataset 0f1ccc4a-9a11-4697-b43f-9c9c8ac543e6 is not available in this repository.
```

**Comment by dickscheid** [comment]
Interestingly enough, this seems to work using the same token
```
from siibra.retrieval import EbrainsPublicDatasetConnector
c = EbrainsPublicDatasetConnector("0f1ccc4a-9a11-4697-b43f-9c9c8ac543e6")
```
which is unexpected, since the connectivity fetcher seems to do just the same:
https://github.com/FZJ-INM1-BDA/siibra-python/blob/8f899ff72b470c6fa359061a6bf80d0f2994cc23/siibra/features/connectivity.py#L205

Need to look more into it.

**Comment by dickscheid** [comment]
This issue is related to different scopes of EBRAINS auth tokens, which allow to do successful queries for either the old knowledge graph version 2, or the new knowledge graph version 3, or both. The scope depends on the service / endpoint being used for fetching a token. We are investigating the exact combinations to test this, update the documentation accordingly, and hopefully provide helpful error messages in such cases.

**Comment by AhmetNSimsek** [comment]
Not reproducable as of c8908901c9cc897fb5fd5ed44d6749048ca1fa78. Probably was fixed with refactoring.
