### ISSUE TITLE
Implement access to all linked EBRAINS features in python client

### ISSUE THREAD

**Issue by xgui3783** [FZJ-INM1-BDA/siibra-python#21]

**Comment by xgui3783** [comment]
In order to achieve this, region id should be included in the config, and parsed properly

**Comment by dickscheid** [comment]
@xgui3783 this works in current release, although it admittedly needs a bit more streamlining. See e.g. the example notebook at https://github.com/FZJ-INM1-BDA/siibra-python/blob/main/examples/Walkthrough.ipynb at version 63f5141, near the very end. Can we close this?

**Comment by xgui3783** [comment]
just checked, yes it's MVP in my opinion in v0.1v4. closing issue.
