### ISSUE TITLE
[bug] ContinuousParcellationVolume.decode_region returns region, rather than index

### ISSUE THREAD

**Issue by xgui3783** [FZJ-INM1-BDA/siibra-python#219]
per https://github.com/FZJ-INM1-BDA/siibra-tutorials/blob/6fb52ea/01-BasicConcepts.ipynb

```python
# vice versa, what is the index of that region?
pmaps.decode_region('hoc5 left')
```

decode_region returns a region, not mapindex

**Comment by AhmetNSimsek** [comment]
As of version 0.4:
`get_index(regionspec)` returns the `MapIndex` of a particular region. It fails when there are multiple matches to the regionspec. `find_indicies` can be used to get a list of MapIndicies matching to the regionspec.
`get_region(label, volume, fragment)` returns the region object corresponding to the particular MapIndex.
