### ISSUE TITLE
Fail gracefully if any external repository (EBRAINS, Allen) is down and data is not cached

### ISSUE THREAD

**Issue by xgui3783** [FZJ-INM1-BDA/siibra-python#22]
relevant trello card: https://trello.com/c/qMbrbBPX/66-make-sure-all-components-fail-gracefully-if-kg-is-down-and-data-is-not-cached

**Comment by dickscheid** [comment]
see also #4 which has been closed as a duplicate

**Comment by xgui3783** [comment]
well, as gracefully as we can be. 

I would say this can be marked as finished
