### ISSUE TITLE
hcp bundle statistic map may have wrong affine

### ISSUE THREAD

**Issue by xgui3783** [FZJ-INM1-BDA/siibra-python#249]
code to reproduce:

```python
import siibra, nilearn
with siibra.QUIET:  # suppress progress output
    hcp_maps= siibra.get_map(
        space="mni152", parcellation=siibra.parcellations.SHORT_FIBER_BUNDLES_HCP, maptype="statistical"
    )
idx = hcp_maps.get_index("rh_MT-MT_4")

from nilearn import plotting
pmap = hcp_maps.fetch(index=idx)
plotting.plot_roi(pmap, cmap='viridis')
```

result:

![download](https://user-images.githubusercontent.com/19381783/214021712-64be90a6-3a0b-4f0c-910c-57e17743599d.png)

**Comment by dickscheid** [comment]
This is a data issue, if at all wrong - cannot be fixed in th software

**Comment by dickscheid** [comment]
btw, one would not extract the index for such queries, you can do
```
hcp_maps.fetch(region="rh_MT-MT_4")
```
to have siibra do that for you. One of the main ideas in siibra is to hide the region/index conversions if not strictly needed.

**Comment by dickscheid** [comment]
It seems to be an unexpected affine indeed. I tested with the other hemisphere
```
pmap = hcp_maps.fetch(region="lh_MT-MT_4")
plotting.plot_roi(pmap, cmap='viridis')
```
and the shift is towards the white matter, suggesting a vertical shift indeed.

**Comment by dickscheid** [comment]
I informed Neurosen about the issue, waiting for their response, but we don't keep this blocking a v0.4 release since it will be fixed on the data side most probably.

**Comment by AhmetNSimsek** [comment]
These show “rh_MT-MT_4” statistical map and short-bundles_withSulciMask (from Ebrains 6a7e07ad-303c-4b1d-b444-ded9ee782225) on mni_icbm152_t1_tal_nlin_asym_09c template.
(The template is taken from http://www.bic.mni.mcgill.ca/~vfonov/icbm/2009/mni_icbm152_nlin_asym_09c_nifti.zip).

![rh_MT-MT_4-coronal](https://github.com/FZJ-INM1-BDA/siibra-python/assets/69900321/0861789f-8879-413d-a668-6d9c467e6489)
![rh_MT-MT_4-axial](https://github.com/FZJ-INM1-BDA/siibra-python/assets/69900321/28c0d11a-4ca8-4eb9-bea4-43482be8f81e)
![short-bundles_withSulciMask](https://github.com/FZJ-INM1-BDA/siibra-python/assets/69900321/d43a2436-ef6f-4552-a865-36f2e7fc50f3)

**Comment by AhmetNSimsek** [comment]
https://jugit.fz-juelich.de/t.dickscheid/brainscapes-configurations/-/commit/fccfe25ecc1bac82acd86ab3987697d69833d92f solves this issue. Will be availbale with v0.4a62
