### ISSUE TITLE
Caching includes auth token in hash

### ISSUE THREAD

**Issue by dickscheid** [FZJ-INM1-BDA/siibra-python#25]
The cached_get implementation in request uses all kwargs for creating the hash. This includes the authentication token for EBRAINS queries, which is not elegant as it iwll refuse to use the cached data if the HBP_AUTH_TOKEN is not set any more.

**Comment by marcenko** [comment]
Is this still the case? I was looking into the code, but couldn't find the right place where this happens.

**Comment by AhmetNSimsek** [comment]
Not an issue as of v0.4
