### ISSUE TITLE
[chore] add token to codecov CI

### ISSUE THREAD

**Issue by xgui3783** [FZJ-INM1-BDA/siibra-python#261]
In order to prevent

false positive in tests: https://github.com/FZJ-INM1-BDA/siibra-python/actions/runs/4111966133/jobs/7096311370

**Comment by AhmetNSimsek** [comment]
I think this is already done: 3bef0ddd9d56d446b3bc6a5494f977aa39862c4f

**Comment by xgui3783** [comment]
actually, seems to be very heisenburg

see issue: https://github.com/codecov/codecov-action/issues/598

I think I read somewhere that it could be rate limiting issue. 

adding access token *should* solve the issue.

**Comment by AhmetNSimsek** [comment]
It seems adding a token won't solve the issue as it is a solution for private repos.

**Comment by AhmetNSimsek** [comment]
solved with https://github.com/FZJ-INM1-BDA/siibra-python/pull/616 and adding new codecov secret.
