### ISSUE TITLE
Irregular centroid coordinate for LB (Amygdala) right

### ISSUE THREAD

**Issue by SBludau** [FZJ-INM1-BDA/siibra-python#268]
For LB (Amygdala) right the centroid coordinate is located nearly outside the pmap

https://interactive-viewer.apps.hbp.eu/#/a:juelich:iav:atlas:v1.0.0:1/t:minds:core:referencespace:v1.0.0:dafcffc5-4826-4bf1-8ff6-46b8a31ff8e2/p:minds:core:parcellationatlas:v1.0.0:94c1125b-b87e-45e4-901c-00daee7f2579-290/r:_cee28db::2x/@:0.0.0.-W000.._eCwg.2-FUe3._-s_W.2_evlu..7LIy..rP_0.Mus0~.1RZO0~..1LSm

The centroid on the left side of LB (Amygdala) seems to be correct.

https://interactive-viewer.apps.hbp.eu/#/a:juelich:iav:atlas:v1.0.0:1/t:minds:core:referencespace:v1.0.0:dafcffc5-4826-4bf1-8ff6-46b8a31ff8e2/p:minds:core:parcellationatlas:v1.0.0:94c1125b-b87e-45e4-901c-00daee7f2579-290/r:_66981ff2::2x/@:0.0.0.-W000.._eCwg.2-FUe3._-s_W.2_evlu..7LIy..1aKyC~.99sf~.1euPi~..1LSm

**Comment by SBludau** [comment]
The problem was found by user who contacted me via ebrains webpage. There might be more problems within the amygdala. Maybe some areas are not grouped correctly? For the IF Amygdala structure there is indeed no centroid available in siibra.

<html><body>
<div style="font-family: Calibri, Arial, Helvetica, sans-serif; font-size: 12pt; color: rgb(0, 0, 0); background-color: rgb(255, 255, 255);" class="elementToProof">
<br class="ContentPasted1">


  |   | MANGO visualizer |   | SIIBRA (physical space)
-- | -- | -- | -- | --
left amygdala | CM | -23 | -4 | -13 |   | -18,9 | -9,5 | -11,1
IF | -29 | -3 | -18 |   | no centroid | no centroid | no centroid
LB | -26 | -3 | -24 |   | -26,3 | -2,4 | -27,5
MF | -20 | -8 | -15 |   | -18,7 | -10,8 | -17,5
SF | -19 | -1 | -21 |   | -17,0 | -3,8 | -21,5
VTM | -25 | -11 | -15 |   | -23,3 | -11,9 | -19,3
  |   |   |   |   |   |   |   |  
right amygdala | CM | 22 | -4 | -13 |   | 18,6 | -8,4 | -11,0
IF | 27 | -1 | -18 |   | no centroid | no centroid | no centroid
LB | 25 | -1 | -24 |   | 14,0 | -6,0 | -24,0
MF | 18 | -7 | -15 |   | 17,6 | -11,2 | -18,2
SF | 18 | 0 | -20 |   | 17,0 | -0,7 | -21,4
VTM | 23 | -10 | -16 |   | 22,7 | -11,4 | -19,4


<br>
</div>
<div class="elementToProof">
<div style="font-family: Calibri, Arial, Helvetica, sans-serif; font-size: 12pt; color: rgb(0, 0, 0);">
</div></div>
</body>
</html>

I did not check all of the coordinates until now!

**Comment by xgui3783** [comment]
This is a problem that persisted on older version of siibra-python (<=0.3a27). 

We are currently working to adapt to the newest version, which should see this issue addressed.

**Comment by AhmetNSimsek** [comment]
Note that IF Amygdala structure is not available in the original nifti from the dataset.

**Comment by AhmetNSimsek** [comment]
As of a6fdbc752286e073e8cc30511c94e214ce58a6b1

| Region | SIIBRA  x | y | z |
| ------- | ------------------------- | - | - |
| LB right | 25,3 | -2,19 | -27,1 |


```python
import siibra
p = siibra.parcellations['julich 2.9']
r = p.get_region('LB left')
print(r.compute_centroids(siibra.spaces['mni152']).points[0])
```
