### ISSUE TITLE
[bug] regional connectivity have same id's

### ISSUE THREAD

**Issue by xgui3783** [FZJ-INM1-BDA/siibra-python#269]
commit: f43192d38e72e15ae5465bad3baeb92ac8400c7e

to reproduce:

```python
import siibra
features = siibra.features.get(siibra.parcellations['2.9'], "RegionalConnectivity")
assert len(features) == len({ f.id for f in features }), f"{len(features)} features, but only {len({ f.id for f in features })} unique id's"
```

**Comment by AhmetNSimsek** [comment]
The data is different and the issue lies in how `feature.id` and `feature.name` are defined. Can be solved by a more descriptive `feature.name`.

**Comment by xgui3783** [comment]
To raise some ideal property of the `id` property (pun intended)

- must be unique
- must be immutable (i.e. cannot use memory address, cannot use array/list index)
- must be quick to compute (i.e. cannot be computed by hashing underlying data, which are often network bound)

**Comment by xgui3783** [comment]
use file hash to compute feature id

the file hash has already been added to snapshot, but integrating into feature id still needs to be implemented
