### ISSUE TITLE
[question] should parcellation introduce `groupBy` functionality

### ISSUE THREAD

**Issue by xgui3783** [FZJ-INM1-BDA/siibra-python#28]
in siibra-explorer, parcellations are (sometimes) grouped according to, say, functional modes, fiber bundle. Should siibra-python also have this functionality?

If yes to above, how should this be implemented?

- with a parcellation.label attribute, which expects a list of string, so user can filter by label
- with a pseudo path as a string attribute, and the client can reconstruct the tree, to allow for a hierarchy organisation of parcellation
- other suggestions?

pinging @dickscheid @marcenko @skoehnen

**Comment by dickscheid** [comment]
I think that this should be stored as a "modality" attribute of the parcellation (cytoarchitecture, function, fibre architecture, structurual connectivity, functional connectiviy, multimodal)

**Comment by xgui3783** [comment]
perfect! this would actually solve another issue that daviti and I are discussing. 

I can create a quick PR for this?

**Comment by xgui3783** [comment]
I will update the configration repo first. 

To ensure naming consistency, here are the possible values I will add to every `parcellation.modality` (`modalities` ? should this be a list, to be future proof? in the event that some parcellation may have a combination of modalities?) 

- cytoarchitecture (julich brain v1.18, julich brain v2.5)
- fibre architecture (long bundle, short bundle, hcp bundle)
- functional modes (difumo [] )

these do not  yet have modalities assigned:
- cortical layers
- isocortex
- dk

**Comment by xgui3783** [comment]
fixed by #32
