### ISSUE TITLE
Feature configuration folder system does not work when using local configuration on Windows

### ISSUE THREAD

**Issue by AhmetNSimsek** [FZJ-INM1-BDA/siibra-python#292]
When one uses local configuration folders on Windows, the configuration folders take the shape 'features\\connectivity\\regional\\streamlinelengths' instead of 'features/connectivity/regional/streamlinelengths'. This breaks the usage of a local configuration of the feature conf_folder system. Note that this is not an issue for atlases, maps, etc. as they are shipped in single folder.

**Comment by xgui3783** [comment]
the following needs to be retrofitted using os independent:

- [ ] feature boostrap folder
- [ ] accessing ebrains snapshot

**Comment by AhmetNSimsek** [comment]
solved with #482
