### ISSUE TITLE
[bug] merged map do not have the same shape, or dtype

### ISSUE THREAD

**Issue by xgui3783** [FZJ-INM1-BDA/siibra-python#302]
as of 0.4a35

when merge labelled map, the returned nifti has the wrong shape and dtype

sample code:

```python
import siibra
labelled_map = siibra.get_map("2.9", "152", "labelled")
vol_l = labelled_map.fetch(fragment="left hemisphere")
vol_r = labelled_map.fetch(fragment="right hemisphere")
vol_b = labelled_map.fetch()

assert vol_l.dataobj.dtype == vol_r.dataobj.dtype == vol_b.dataobj.dtype # datatype differs (uint16, uint16, float64)
assert vol_l.dataobj.shape == vol_r.dataobj.shape == vol_b.dataobj.shape # shape differs ( (193, 229, 193), (193, 229, 193),  (289, 361, 271) )
```

**Comment by AhmetNSimsek** [comment]
Note: `labelled_map.compress()` fetches the merged map as well and returns the correct shape. Looking into it.

**Comment by AhmetNSimsek** [comment]
as of v0.4a41
`NiftiProvider._merge_fragments` creates a new nifti image before merging the fragments. During this, the dimensions are calculated via `voxdims = np.dot(np.linalg.inv(original_affine), np.r_[self.bbox.shape, 1])[:3]`.

Note: The merge is successful even when the original shape is taken.

Next: will compare the compressed map image and merged to see the exact difference
