### ISSUE TITLE
`RegionProps` constructor returns error for hemisphere'ed region(s)

### ISSUE THREAD

**Issue by xgui3783** [FZJ-INM1-BDA/siibra-python#31]
version/hash: 6831d2df53fe5715738ccb752604fcdfabc32340

to reproduce:

```python
import siibra as sb
atlas=sb.atlases.MULTILEVEL_HUMAN_ATLAS
atlas.select_region('4p left')
regionprop=sb.region.RegionProps(
    atlas.selected_region,
    sb.spaces.MNI152_2009C_NONL_ASYM
)
```

expected result: returns regionprop

actual result: AttributeError: 

```
[siibra:WARNING]  No mask could be computed for Area 4p (PreCG) - left hemisphere
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/xiao/dev/projects/siibra-api/venv/lib/python3.6/site-packages/siibra/region.py", line 488, in __init__
    M = np.asanyarray(mask.dataobj) 
AttributeError: 'NoneType' object has no attribute 'dataobj'
```

some diagnosis seems to suggest that `ParcellationMap` is indexed by non hemisphered region (ie, parent node of `4p left`)

**Comment by dickscheid** [comment]
Confirmed. This had been fixed in an earlier version already, and included an update to the confiugration files which had been messed up when merging branches of the configuration repository. I will fix it on develop.

**Comment by dickscheid** [comment]
This error should now be fixed on develop. @xgui3783 could you check this again?
