### ISSUE TITLE
[bug] attempt to fetch volumes with multiple sources can occassionally result in undeterministic behaviour

### ISSUE THREAD

**Issue by xgui3783** [FZJ-INM1-BDA/siibra-python#318]
as of 0.4a35

When volume with multiple providers (e.g. nii + neuroglancer/precomputed) calls fetch, network conditions will determine which provider is used. 

e.g. for [mni152 jb29 labelled](https://jugit.fz-juelich.de/t.dickscheid/brainscapes-configurations/-/blob/siibra-0.4a35/maps/mni152-jba29-labelled.json#L11-19) where both nii and precomputed are provided, nii will be attempted first (per https://github.com/FZJ-INM1-BDA/siibra-python/blob/01d3d09/siibra/volumes/volume.py#L40-L44 ). If it fails (src is unreachable, in maintenance, being rate limited), neuroglancer precomputed source will be used. 

precomputed provider fetch seems to default to lowest resolution.

As a result, voxel count will likely be a factor of 8 less.

code to reproduce:

caveat:
- need to install test dep `requests-mock`
- needs to run `siibra.cache.clear()` between each run

```python
import siibra
import numpy as np
import requests_mock

siibra.cache.clear()

url = "https://neuroglancer.humanbrainproject.eu/precomputed/data-repo-ng-bot/20210714-julichbrain_v290_correctaffine/hbp-d000007_julichbrain-cytoatlas_dev/MPMs/29.0/GapMapPublicMPMAtlas_l_N10_nlin2StdICBM152asym2009c_29_publicDOI_b1bcc0b5a127f5a917f0d8b0e869be5d.nii.gz"

def main():
    region = siibra.get_region("2.9", "area 1 (postcg) left")
    rmap = region.fetch_regional_map("mni152")
    print(np.count_nonzero(rmap.get_fdata()))

def mocked():
    with requests_mock.Mocker(real_http=True) as mocker:
        mocker.register_uri(url=url, method="get", status_code=404, text="oh no")
        main()

main() # prints 6203

```

clear siibra cache

```python
import siibra
import numpy as np
import requests_mock

siibra.cache.clear()

url = "https://neuroglancer.humanbrainproject.eu/precomputed/data-repo-ng-bot/20210714-julichbrain_v290_correctaffine/hbp-d000007_julichbrain-cytoatlas_dev/MPMs/29.0/GapMapPublicMPMAtlas_l_N10_nlin2StdICBM152asym2009c_29_publicDOI_b1bcc0b5a127f5a917f0d8b0e869be5d.nii.gz"

def main():
    region = siibra.get_region("2.9", "area 1 (postcg) left")
    rmap = region.fetch_regional_map("mni152")
    print(np.count_nonzero(rmap.get_fdata()))

def mocked():
    with requests_mock.Mocker(real_http=True) as mocker:
        mocker.register_uri(url=url, method="get", status_code=404, text="oh no")
        main()

mocked() # prints 757
```

**Comment by xgui3783** [comment]
I can still reproduce the bug from https://github.com/FZJ-INM1-BDA/siibra-python/commit/df51a05cbe7a3384fb69aa2f9676de807da46ae9

the key is, one need to clear the cache between each run, otherwise, the cached map skew the test result.

I have clarified that in the original issue.

**Comment by xgui3783** [comment]
hmm did you restart your interpreter between each run?

**Comment by AhmetNSimsek** [comment]
Yes, I have. I tried again now and always gives me 6203. I tried with the current main (https://github.com/FZJ-INM1-BDA/siibra-python/commit/051e7ec270550152a0d763eeb0414c2b88627f54) and it then sometimes prints 757 but for both.

It could be OS-specific indeed.

**Comment by xgui3783** [comment]
> Yes, I have. I tried again now and always gives me 6203. I tried with the current main ([051e7ec](https://github.com/FZJ-INM1-BDA/siibra-python/commit/051e7ec270550152a0d763eeb0414c2b88627f54)) and it then sometimes prints 757 but for both.
> 
> It could be OS-specific indeed.

I suspect this is because the cache was not cleared. 

I was not super clear on how to reproduce the issue when I first posted it. I have since updated it. 

Can you try the following code:

```python
import siibra
import numpy as np
import requests_mock

siibra.cache.clear()

url = "https://neuroglancer.humanbrainproject.eu/precomputed/data-repo-ng-bot/20210714-julichbrain_v290_correctaffine/hbp-d000007_julichbrain-cytoatlas_dev/MPMs/29.0/GapMapPublicMPMAtlas_l_N10_nlin2StdICBM152asym2009c_29_publicDOI_b1bcc0b5a127f5a917f0d8b0e869be5d.nii.gz"

def main():
    region = siibra.get_region("2.9", "area 1 (postcg) left")
    rmap = region.fetch_regional_map("mni152")
    print(np.count_nonzero(rmap.get_fdata()))

def mocked():
    with requests_mock.Mocker(real_http=True) as mocker:
        mocker.register_uri(url=url, method="get", status_code=404, text="oh no")
        main()

mocked() # prints 757
```

**Comment by AhmetNSimsek** [comment]
> Can you try the following code:
This produces 757

**Comment by AhmetNSimsek** [comment]
How about adding a `base_resolution` parameter in json (under provider section) for each precomputed neuroglancer image? If there is nothing, then it will still do default behaviour (go to the lowest). But if there is a value, then it will use it.
Since we have to compute the neuroglancer volumes anyway, this could be outputted during the pipeline.

What do you think @xgui3783  and @dickscheid?

**Comment by xgui3783** [comment]
I do not like that we are expanding the base schema so much. 

in no time we will not remember why we added the attributes. 

I proposed the following to resolve the issue:

rather than trying the volume sources one by one, if no spec is provided try and retry the first in the order of preference, only. 

we do not introduce more schema we need to maintain, and improve the reproducibility.

**Comment by AhmetNSimsek** [comment]
I see what you mean. Do you think the retry window would be enough for a network issue?

**Comment by xgui3783** [comment]
> I see what you mean. Do you think the retry window would be enough for a network issue?

I argue that thrown error is better than silent breakdown of reproducibility

**Comment by AhmetNSimsek** [comment]
Ahhh you mean never actually try other sources and throw an error?

**Comment by xgui3783** [comment]
> Ahhh you mean never actually try other sources and throw an error?

Correct. Unless the user specifically requests `format=neuroglancer/precomputed`

**Comment by AhmetNSimsek** [comment]
Okay now I get what you mean. Makes sense. I'll make the change

**Comment by AhmetNSimsek** [comment]
#391 provides a solution.
TODO:
- [ ] add a unit test
- [ ] add e2e (https://github.com/FZJ-INM1-BDA/siibra-python/pull/367)
