### ISSUE TITLE
[enhancement] Maps should have an InstanceTable as well

### ISSUE THREAD

**Issue by AhmetNSimsek** [FZJ-INM1-BDA/siibra-python#329]
Instance tables provide a great way to check the existing configuration concepts. However, for maps, this has been lacking due to their inherit complexity. @dickscheid and I had discussed this before and had considered an upgrade to the instance tables by making them a data frame that stores extra information such as species. The branch [attrDFforMaps](https://github.com/FZJ-INM1-BDA/siibra-python/tree/attrDFforMaps) introduces such a data frame to maps while instance tables are still used for the core concepts. This branch is made to facilitate the discussion:
- Should all the InstanceTables be replaced by such a data frame? (In such a case, the naming InstanceTable will be preserved.)
- What else can we improve for the maps InstanceDF?
- Should we change the naming of the statistical map files in the configuration? (continuous<->statistical)
- Thoughts about a similar table for features?

Code example:
```python
import siibra
print(siibra.maps.head())
print(siibra.maps.columns)
print(siibra.maps.index)
siibra.maps.query("space == 'MNI Colin 27'")
```

PS: The original code is authored by @dickscheid.

**Comment by xgui3783** [comment]
Just occurred to me one thing:

> Should all the InstanceTables be replaced by such a data frame? (In such a case, the naming InstanceTable will be preserved.)

I would hate to lose static typing offered by instance table.

**Comment by dickscheid** [comment]
Dataframes are very nice in notebooks to plot the instances with some attributes, but in line with Xiao's comment I think we need to clarify a few important functionalities:

* can we do static typing with this?
* can we do autocompletion on the instance keys a suitable interpreter?

Maybe the solution is to provide a data frame listing optionally, using a dedicated function. Then it could be part of the the atlas concept parent class, and we could keep the instance table.

**Comment by AhmetNSimsek** [comment]
-If we enable static typing, the default `__iter__` has to be replaced. Which then in turn breaks the default representation of dataframes. I am thinking about this currently.

- Autocompletion is currently supported
![image](https://user-images.githubusercontent.com/69900321/237055127-916591c4-0024-47f9-9e0e-168656b950ad.png)

> Maybe the solution is to provide a data frame listing optionally, using a dedicated function. Then it could be part of the the atlas concept parent class, and we could keep the instance table.

I think this might work. I will give it a try and update here

**Comment by xgui3783** [comment]
why not just add `dataframe` as a property to *all* instancetables? this way, we preserve the current behavior, and if the user is more comfortable using a dataframe, they could get one

**Comment by AhmetNSimsek** [comment]
If we make it a property, registers `siibra.maps.dataframe` for static typing.

But function works just fine, see https://github.com/FZJ-INM1-BDA/siibra-python/pull/364/commits/6cd227ad727772c66a49c8c590c3399183a33da2

PS: It can be less ugly I think. I am checking how this looks with features and then will work on cleaning up.

**Comment by AhmetNSimsek** [comment]
> > If we make it a property, registers siibra.maps.dataframe for static typing.
> 
> not too sure what is the issue with using a `@property` decorator?

I tried but `siibra.maps.dataframe` raised AttributeError. I'll check again if it was a typo on my side or alike

**Comment by AhmetNSimsek** [comment]
It was an error on how I initially created dataframe property. A new [commit ](https://github.com/FZJ-INM1-BDA/siibra-python/pull/364/commits/206f26cc74ad1f79c389e644858b52f34c476f46) is pushed now
