### ISSUE TITLE
issues with installing siibra via pip

### ISSUE THREAD

**Issue by LeonMpunkt** [FZJ-INM1-BDA/siibra-python#33]
Hi, 

when installing siibra via the pip command, I think the wrong version of numpy gets installed alongside:

```python
Successfully installed numpy-1.16.6
```
even when the newest numpy version was previously installed.

When trying to import siibra the following error occurs:

```python
ValueError: numpy.ndarray size changed, may indicate binary incompatibility. Expected 88 from C header, got 80 from PyObject
```

after manually installing the newest numpy version subsequently to the siibra installation, the siibra import works.

Best
L

**Comment by xgui3783** [comment]
seems like the issue reported at https://github.com/FZJ-INM1-BDA/siibra-python/issues/14#issuecomment-825413037 was not isolated.

Can you report your 

```sh
python --version
pip --version
```

so we can better diagnose the issue?

**Comment by LeonMpunkt** [comment]
pip 21.0.1 from /opt/anaconda3/lib/python3.8/site-packages/pip (python 3.8)

do you think updating both will solve it?

**Comment by xgui3783** [comment]
I think python 3.8 should be well supported. We will try to investigate how this error occurred.

**Comment by xgui3783** [comment]
mm, strange, within a fresh docker environment, `pip install siibra` seems to install the correct version of numpy:

```sh
root@9430c220ffe5:/# python --version
Python 3.8.10
root@9430c220ffe5:/# pip --version
pip 21.1.1 from /usr/local/lib/python3.8/site-packages/pip (python 3.8)
root@9430c220ffe5:/# pip install siibra
# ... (truncated for brevity)...
Collecting numpy>=1.13.3
  Downloading numpy-1.20.2-cp38-cp38-manylinux2010_x86_64.whl (15.4 MB)
# ...(truncated for brevity)...
```

I wonder if

- in conda environment, depedency resolution works differently (unlikely)
- dep resolution is wonky (siibra explicitly requires numpy>=1.20 per https://github.com/FZJ-INM1-BDA/siibra-python/blob/fe99abecb364583c6732fa64046d69659b15955f/requirements.txt#L1), but even in the working example, it seems to try to install numpy >= 1.13

I am inclined to believe it is the latter, but my python foo is rather limited. I will ask around to see if anyone knows better about how python does dependency resolution
