### ISSUE TITLE
Comparison of Region with different type raises an exception

### ISSUE THREAD

**Issue by ch-schiffer** [FZJ-INM1-BDA/siibra-python#342]
I noticed that the Region class raises an exception when being compared to an object that is not a Region. Consider the following example:

```python
parcellation = siibra.parcellations.get("julich 2.9")
r1 = parcellation.get_region("hOc1")
r2 = parcellation.get_region("hOc2")

r1 == r2 # this works, because r1 and r2 have the same type
r1 == "hOc1" # works as well, string is handled
r1 == 2 # raises a ValueError, because int is not handled
```

In my opinion, a comparison to an unknown type should return False, not raise an exception. You also would not expect `4 == "four"` to raise an exception, just return false.

As a consequence, the following checks fails with a ValueError:

```python
some_list = [1, 3, "hOc1", r1]
region_in_some_list = r1 in some_list # fails, cannot compare 1 to Region

some_other_list = [r1, r2]
filtered_list = [r for r in some_other_list if r in some_list] # fails as well, cannot compare 1 to Region
```

I would simply suggest to replace the ValueError here https://github.com/FZJ-INM1-BDA/siibra-python/blob/main/siibra/core/region.py#L184 with `return False`.

**Comment by AhmetNSimsek** [comment]
It does align with the default Python behavior for `__eq__`. 
@dickscheid, was there a specific design decision behind the current version?

**Comment by dickscheid** [comment]
I agree with Christian's proposal, should be changed.
