### ISSUE TITLE
support for other atlases (mainly rodent, for the time being)

### ISSUE THREAD

**Issue by xgui3783** [FZJ-INM1-BDA/siibra-python#35]
currently siibra-python only supports human multilevel atlas. 

In order to reach feature parity with the existing siibra-explorer, siibra-python will need to support rodent atlases (Waxholm rat and Allen mouse)

**Comment by xgui3783** [comment]
indeed. PR to introduce rat and mouse were merged recently: https://jugit.fz-juelich.de/t.dickscheid/brainscapes-configurations/-/merge_requests/4

awaiting on #37 to close this issue

**Comment by dickscheid** [comment]
@xgui3783 while rat and mouse need more streamlining, the basics are there. Can we close this issue for now?

**Comment by xgui3783** [comment]
agreed. closing issue.
