### ISSUE TITLE
[discussion] use plotly as a visualization grammar for plots to be also transferred by the api

### ISSUE THREAD

**Issue by AhmetNSimsek** [FZJ-INM1-BDA/siibra-python#350]

**Comment by xgui3783** [comment]
[meta]

do we use discussion feature, or rely exclusive on issues?

if we do not expect to use discussion, we should disable discussion tab altogether

[/meta]

alternatives include:

- plotly

**Comment by ch-schiffer** [comment]
Commenting on plotly vs. vega: I tried both `vega` (through `altair` python library) and `plotly`, and my personal favorite is `plotly`. Both offer nice interactivity, which is a huge plus over for example matplotlib, but I found `plotly` just way easier to work with and understand, and I liked the documentation better.
`altair` does its best to hide away some of the details of vega (which is a good thing in my opinion, I cannot imagine writing vega directly to be fun), but at times it still feels like writing a quite verbose specification for the plot.

**Comment by AhmetNSimsek** [comment]
Decided to use `plotly`

**Comment by AhmetNSimsek** [comment]
Note that `pandas` can use `plotly` as the backend visualization grammar by `pd.options.plotting.backend = "plotly"`. For simplicity and keeping requirements of siibra-python low, [a prototype implementation](https://github.com/FZJ-INM1-BDA/siibra-python/tree/implementPlotly) has been written.
If plotly is installed in the environment, the plot functions use plotly and return as a `plotly.graph_objects.Figure`. This object has `to_json()` method which can be used for `siibra-api`.
@xgui3783, when you have time, could you please test this?

**Comment by xgui3783** [comment]
can you raise a draft PR already? so we can keep the discussion in the PR, rather than in this issue?

**Comment by AhmetNSimsek** [comment]
As of 5004e69597d89f74bdaec7fcc184737ed71c57e7, Plotly has been implemented in general.
TODO: make sure all plots in pyplot preserve the settings of style settings of matplotlib.

**Comment by AhmetNSimsek** [comment]
Continued at #429
