### ISSUE TITLE
incorrect version of Julich-Brain MPM being used in siibra-config

### ISSUE THREAD

**Issue by xgui3783** [FZJ-INM1-BDA/siibra-python#36]
this is mainly a reminder to address https://jugit.fz-juelich.de/t.dickscheid/brainscapes-configurations/-/issues/2 , because, the current config points to an older version of julich brain.

**Comment by dickscheid** [comment]
Solved by v0.1a6, b9f011449c2140923380c96fb428fb7da62d311c
