### ISSUE TITLE
Wrong delimiter for decoding .csv files

### ISSUE THREAD

**Issue by man-shu** [FZJ-INM1-BDA/siibra-python#365]
The delimiter should be `,` instead of `;` here: https://github.com/FZJ-INM1-BDA/siibra-python/blob/e40973b26e2cc62035ddaff542eb86fbda8674fa/siibra/retrieval/requests.py#L55

**Comment by AhmetNSimsek** [comment]
@man-shu, thank you for your comment. Could you please describe the issue you are having further?

**Comment by man-shu** [comment]
Hi @AhmetNSimsek. Thanks for the prompt response.

The issue is that when I fetch a CSV file, the loaded pandas dataframe is weird because of the wrong delimiter in the decoder:

**Comment by AhmetNSimsek** [comment]
Hi @man-shu,
could you please share how are you fetching the file with a sample code? I think I can be of better help then.

**Comment by man-shu** [comment]
Sorry, just updated my comment! Accidentally posted it while changing lines...

**Comment by AhmetNSimsek** [comment]
No problem :)
I understand that when the delimiter is wrong, the file be read incorrectly. Excuse the miscommunication, I meant how do you use siibra to load the csv?

Siibra can handle different delimiters but depends on how you are loading the data. Have you prepared a preconfiguration json?

**Comment by man-shu** [comment]
Here's the code I am using to get output above:

```python
import siibra
from siibra.retrieval.repositories import EbrainsHdgConnector

siibra.fetch_ebrains_token()

dataset_id = "07ab1665-73b0-40c5-800e-557bc319109d"

connector = EbrainsHdgConnector(dataset_id)

db_file = "resulting_smooth_maps/ibc_neurovault.csv"

db = connector.get(db_file)

db
```

**Comment by AhmetNSimsek** [comment]
Thank you.
In such a case, you can use the following to adjust some parameters according to the dataset:
```python
import pandas as pd
from io import BytesIO
connector.get(db_file, decode_func=lambda b: pd.read_csv(BytesIO(b), delimiter=","))
```
`decode_func` replaces the defaults. Unfortunately, there are usually a few reasons behind using `;` as a default delimiter for csv's.
Please let me know if this works for you.

**Comment by man-shu** [comment]
I was using this workaround for now but just thought it might be more intuitive to use `,` instead of `;` as default. Just out of curiosity, in what ways can `;` be more useful?

**Comment by xgui3783** [comment]
hmm, judging by [the commit](https://github.com/FZJ-INM1-BDA/siibra-python/commit/c0788ac90f594b1bd98ae6cbb5f9687928c932fe) that introduced the csv decoder, it appears that the deocder was original written to parse 1000 brains data. 

Despite its name, there exist csv's in the wild (in this case, most likely the 1000 brain data), which uses other characters, such as `;` (and indeed, also ` ` (single white space), `\\s+` (column aligned with white space) 

But I agree that the decoder should at least recognise `,`.

**Comment by AhmetNSimsek** [comment]
#381 addressed this issue.
