### ISSUE TITLE
[documentation][refactor] Space.get_template, format kwarg has no effect

### ISSUE THREAD

**Issue by xgui3783** [FZJ-INM1-BDA/siibra-python#385]
as of 5a649faf94f07abcd91c0c8979a58bcd07b9c7bf

despite the [docstring](https://github.com/FZJ-INM1-BDA/siibra-python/blob/5a649faf94f07abcd91c0c8979a58bcd07b9c7bf/siibra/core/space.py#L84-L105) , format keyword arg does not affect the return value.

This could be an issue, if user expects to retrieve nii template, provided it as a keyword arg, but it ends up being non relevant.

**Comment by AhmetNSimsek** [comment]
Yes, it should be removed from the keyword args and the docstring. The format selection should happen with `fetch`.

**Comment by AhmetNSimsek** [comment]
1beebbab6262e17ed920bdab2fba0783523c3081 addresses this.
