### ISSUE TITLE
[bug][regression] map.publications raises an exception

### ISSUE THREAD

**Issue by xgui3783** [FZJ-INM1-BDA/siibra-python#404]
as of 26301e17f3c98087670347939194fbb86d57e1ae (also fails at 3ffad38)

sample code:

```python
import siibra
m = siibra.get_map("2.9", "colin", "labelled")
m.publications
```

expected: returns publications (even if empty list)

actual result: raises

**Comment by xgui3783** [comment]
added test cases: https://github.com/FZJ-INM1-BDA/siibra-python/pull/405

**Comment by AhmetNSimsek** [comment]
Found the bug. Pushing a fix soon

**Comment by AhmetNSimsek** [comment]
4e2ee71a9ad4e886c4638bc5f85625caf85e0bca fixes it
