### ISSUE TITLE
Not all spaces/parcellations have desc/publications

### ISSUE THREAD

**Issue by xgui3783** [FZJ-INM1-BDA/siibra-python#411]
as of v0.4a59

min repro:

```python
import pytest
import siibra

all_spaces = [
    s for s in siibra.spaces
]

@pytest.mark.parametrize('space', all_spaces)
def test_has_desc(space: siibra.core.space.Space):
    assert space.description, f"{space.name!r} does not have desc"

@pytest.mark.parametrize('space', all_spaces)
def test_has_publications(space: siibra.core.space.Space):
    assert len(space.publications) > 0, f"{space.name!r} does not have publication"
```

expected:

test passes

actual: several tests fails

for e2e tests, see https://github.com/FZJ-INM1-BDA/siibra-python/pull/410

**Comment by xgui3783** [comment]
relates to https://github.com/FZJ-INM1-BDA/siibra-explorer/issues/1376

**Comment by AhmetNSimsek** [comment]
Only incomplete remains to be HCP32K space. Will be tracked here https://jugit.fz-juelich.de/t.dickscheid/brainscapes-configurations/-/issues/50
