### ISSUE TITLE
[question] how does one access license

### ISSUE THREAD

**Issue by xgui3783** [FZJ-INM1-BDA/siibra-python#412]
e.g. 

```python
import siibra

space = siibra.spaces['big brain']
```

how do I get the license of the usage of big brain?

**Comment by AhmetNSimsek** [comment]
Is this information stored in Ebrains dataset?

**Comment by xgui3783** [comment]
some are, some are not. 

allen mouse template, for example, does not have a corresponding KG entry. 

we will need to have more robust way of providing this 

(with a possible link, and/or text desc)
