### ISSUE TITLE
EbrainsPublicDatasetConnector fails to work as intended

### ISSUE THREAD

**Issue by AhmetNSimsek** [FZJ-INM1-BDA/siibra-python#414]
```python
from siibra.retrieval.repositories import EbrainsPublicDatasetConnector
siibra.fetch_ebrains_token()
EbrainsPublicDatasetConnector(dataset_id='45689ca2-df48-4260-a908-56a9d4eb344e')
```
The expected output is a repository connector to https://search.kg.ebrains.eu/instances/45689ca2-df48-4260-a908-56a9d4eb344e.

Actual:
"RuntimeError: Dataset id 45689ca2-df48-4260-a908-56a9d4eb344e did not yield a unique match, please fix the dataset specification."

**Comment by xgui3783** [comment]
cannot reproduce, can you check if this is still an issue?

also, I don't think `EbrainsPublicDatasetConnector` is actively in use any more, or?

**Comment by AhmetNSimsek** [comment]
I still have the same issue.

They are not really used indeed. But I can see the use for EbrainsHdgConnector internally.

We can probably remove these connectors if it is not intended to be of use.

**Comment by xgui3783** [comment]
I think I pinpointed the issue. `EbrainsPublicDatasetConnector` queries `Dataset`

`45689ca2-df48-4260-a908-56a9d4eb344e` is the uuid of a `DatasetVersion`

**Comment by AhmetNSimsek** [comment]
It is indeed the case. Works with `854bf4f9-dd08-49e6-af37-768a80295e20`.
