### ISSUE TITLE
Add "How to cite" information

### ISSUE THREAD

**Issue by ch-schiffer** [FZJ-INM1-BDA/siibra-python#423]
I would suggest adding a "How to cite" section to the README, and maybe also to readthedocs.
Even if there is no publication yet, it would make clear which naming to use, and maybe which authors to name.
Same goes for siibra-explorer.

**Comment by AhmetNSimsek** [comment]
Added a citation file and how to cite to readme as of 6547d266b033eb72f04ee8d4e458900b2b9dc5d6
