### ISSUE TITLE
get_colormap error with Julich Brain 3.0.2

### ISSUE THREAD

**Issue by IhsaneB** [FZJ-INM1-BDA/siibra-python#431]
The get_colormap function does not seem to work when using Julich Brain 3.0.2. Running [this example](https://siibra-python.readthedocs.io/en/latest/examples/02_maps_and_templates/005_access_surface_maps.html#sphx-glr-examples-02-maps-and-templates-005-access-surface-maps-py) with Julich brain 3.0.2 instead of 2.9 results in an error on `get_colormap`: `'CorpusCallosumMask left' could not be decoded under 'Julich-Brain Cytoarchitectonic Atlas (v3.0.2)'`. Seems like it tries to color the corpus callosum for some reason, but fails.

**Comment by AhmetNSimsek** [comment]
https://jugit.fz-juelich.de/t.dickscheid/brainscapes-configurations/-/merge_requests/110 fixes this. Will be available with the next version (0.4a62)

**Comment by AhmetNSimsek** [comment]
The issue is solved as of v0.4a62.
Note: Due to the technical requirements of creating an Fsaverage map,  'CorpusCallosumMask' and 'BrainStemMask' were needed. But they are not officially a part of Julich Brain Atlas 3. Therefore, the colormap does not fetch any information on these "regions".
