### ISSUE TITLE
issue with groupby and Region

### ISSUE THREAD

**Issue by ch-schiffer** [FZJ-INM1-BDA/siibra-python#432]
The `assign` function returns a data frame with a column `region`, where the entries are `Region` objects. However, it is not possible to `groupby` this column, as the comparison operator `<` is not defined for `Region`  objects. This is quite inconvenient, as grouping the result by regions is common I would say.

```python
df = map.assign(some_points)
df.groupby("region") # raises an error
```

A workaround is to create a new column based on the region, e.g. `sampled_points["region_key"] = [region.key for region in sampled_points.region]`, but it is tedious to do this all the time. Maybe it is easier to just implement the comparison operator for regions, for example based on the key.

**Comment by xgui3783** [comment]
Perhaps the better approach is to add comparison class methods to atlas concepts?
