### ISSUE TITLE
Issue with finding region in Julich Brain 3.0.2

### ISSUE THREAD

**Issue by ch-schiffer** [FZJ-INM1-BDA/siibra-python#433]
I noticed an "interesting" issue with `get_region` in Julich Brain 3.0.2. The following code simply tries to get a region twice: First using the name (returned by `regions`), then using the returned `Region` object:

```python
julich_brain_map = siibra.parcellations.JULICH_BRAIN_CYTOARCHITECTONIC_ATLAS_V3_0_2.get_map(space=siibra.spaces.MNI_152_ICBM_2009C_NONLINEAR_ASYMMETRIC)
for region_str in julich_brain_map.regions:
    region1 = julich_brain_map.get_region(index=julich_brain_map.get_index(region_str))
    print(region_str, region1.name)
    region2 = julich_brain_map.get_region(index=julich_brain_map.get_index(region1))
```

This code should work, but raises the following error at the `region2 = ...` line:

`NonUniqueIndexError: The specification 'AcbM (Medial Accumbens, Ventral Striatum) left' does not match to any structure mapped in Map: mni152 jba30 labelled`.

The last line of the output is `Medial Accumbens, ventral Striatum left AcbM (Medial Accumbens, Ventral Striatum) left`, showing that the name of this region and the name returned by the `regions` property are different. I suspect this might be the reason for this issue.

**Comment by AhmetNSimsek** [comment]
An extensive list can be found here: https://jugit.fz-juelich.de/t.dickscheid/brainscapes-configurations/-/issues/19

**Comment by AhmetNSimsek** [comment]
Issuse is resolved by `v4a62`. (Note: the Julich brain 3 version is bumped)
```python
import siibra
julich_brain_map = siibra.parcellations.JULICH_BRAIN_CYTOARCHITECTONIC_ATLAS_V3_0_3.get_map(space=siibra.spaces.MNI_152_ICBM_2009C_NONLINEAR_ASYMMETRIC)
for region_str in julich_brain_map.regions:
    region1 = julich_brain_map.get_region(index=julich_brain_map.get_index(region_str))
    print(region_str, region1.name)
    region2 = julich_brain_map.get_region(index=julich_brain_map.get_index(region1))```
