### ISSUE TITLE
[Discussion] Default `plot` method for features

### ISSUE THREAD

**Issue by AhmetNSimsek** [FZJ-INM1-BDA/siibra-python#436]
(Continues from https://github.com/FZJ-INM1-BDA/siibra-python/pull/429#issuecomment-1678817358)
To use the Plotly figures produced by siibra-python, siibra-api currently is being designed to employ `plot` method. While all features except images have a `plot` method, they are not always named `plot`, i.e. `plot_matrix`, or the default siibra-explorer using is different (`polar_plot`). The defaults can be discussed here.

Note: since this is a breaking change for siibra-python, it is better suited for v0.5a.

**Comment by xgui3783** [comment]
this issue can be closed? since the default has been decided?

**Comment by AhmetNSimsek** [comment]
Yes, you are right.
A note on connectivity tho: since plot functionality of connectivity is feature-rich in the explorer, this will require further discussion as we move towards using plotly figures for all features.
