### ISSUE TITLE
Allow sequential relabeling of volumes

### ISSUE THREAD

**Issue by ch-schiffer** [FZJ-INM1-BDA/siibra-python#452]
I often have the need to sequentially relabel volumes. It seems like the `compress` function does this as a "side effect", but it can only be used for volumes with multiple fragments. For single fragment volumes, `compress` cannot be used, and hence there is no way to easily perform sequential relabeling. It would be nice to decouple the relabeling from the `compress` function and make it available for users.

In this context, another nice feature would be to be able to relabel to a given list of regions, e.g. `volume.relabel("hOc1", "hOc2")`, which would return a volume with indices 1 for hOc1 and 2 for hOc2. If there is already such a functionality, I am not aware of it.

**Comment by AhmetNSimsek** [comment]
As of version `1.0axx`, [`siibra.volumes.volume.merge`](https://siibra-python.readthedocs.io/en/latest/autoapi/siibra/volumes/volume/index.html#siibra.volumes.volume.merge) have an optional `labels` parameter which one can supply desired labels for each volume in the list of volumes to be merged. (Volumes for each region can be obtained by `Region.get_regional_map()`). Please let me know if I can help any further.
