### ISSUE TITLE
Precompute regionprops for standard regions

### ISSUE THREAD

**Issue by marcenko** [FZJ-INM1-BDA/siibra-python#5]
Computing the surface area of a region is computationally expensive (marching cubes), but is constant for the same region over time. The spatial properties of brain regions should be precomputed and stored with the parcellation to avoid costly recomputing and the client side.

**Comment by dickscheid** [comment]
It might be cleaner to just extend the caching capabilites, basically memoizing the function call to disk,

**Comment by dickscheid** [comment]
Implemented in 046040466ae07710405f464e4491f0a8027760c0 (from v0.1a6)
