### ISSUE TITLE
Assignment of uncertain points to labelled maps not working

### ISSUE THREAD

**Issue by dickscheid** [FZJ-INM1-BDA/siibra-python#526]
Reported by a user:

When assigning an image or an uncertain point (which siibra then models as an image of a 3D Gaussian) to a labelled map such as the Julich-brain maximum probability map, the resulting assignment table is empty. Assignment to statistical maps works. (applies to pre-1.0 releases, did not verify in 1.0 yet)

**Comment by AhmetNSimsek** [comment]
Could you please share the code, or location along with the julich brain version used?
