### ISSUE TITLE
Use of cached_property

### ISSUE THREAD

**Issue by ch-schiffer** [FZJ-INM1-BDA/siibra-python#527]
A minor suggestion to slim down the code: [functools.cached_property](https://docs.python.org/3/library/functools.html#functools.cached_property) is an easy replacement for the [caching of properties](https://siibra-python.readthedocs.io/en/latest/developer.html#lazy-loading-via-object-properties) that is used very often in siibra.

**Comment by AhmetNSimsek** [comment]
Will be discussed at https://github.com/FZJ-INM1-BDA/siibra-python/issues/459
