### ISSUE TITLE
CI: mirror action is not possible since mirror is currently read only

### ISSUE THREAD

**Issue by AhmetNSimsek** [FZJ-INM1-BDA/siibra-python#612]
Due to server issues, the mirroring was not possible. At the moment, the mirror is read-only. Therefore, the action will fail. This action is disabled and will be enabled when the server of the mirror is restored.

**Comment by stefanonard85** [comment]
Hi @AhmetNSimsek , 

I am Stefano Nardone from BROAD Institute / HMS. I was attempting to use Siibra package in python but I have encountered the following error , see screenshot attached. Will the server of the mirror be restored soon ? and, if not, is there any possible solution to work with the package? 

Thanks in advance for your help and availability.
I wish you a good day.

Kind regards, 
Stefano nardone, PhD
![Capture](https://github.com/user-attachments/assets/89621c6a-1d82-423a-b6cf-40ca7e97f605)

**Comment by AhmetNSimsek** [comment]
> Hi @AhmetNSimsek ,
> 
> I am Stefano Nardone from BROAD Institute / HMS. I was attempting to use Siibra package in python but I have encountered the following error , see screenshot attached. Will the server of the mirror be restored soon ? and, if not, is there any possible solution to work with the package?
> 
> Thanks in advance for your help and availability. I wish you a good day.
> 
> Kind regards, Stefano nardone, PhD ![Capture](https://private-user-images.githubusercontent.com/16965990/385232315-89621c6a-1d82-423a-b6cf-40ca7e97f605.PNG?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzE0MDYzMTksIm5iZiI6MTczMTQwNjAxOSwicGF0aCI6Ii8xNjk2NTk5MC8zODUyMzIzMTUtODk2MjFjNmEtMWQ4Mi00MjNhLWI2Y2YtNDBjYTdlOTdmNjA1LlBORz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTEyVDEwMDY1OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTNkZTFlNThmNjUzOWI4ZTU0OGMwZTUzOWRlYjFjOTllYjVjYmM4M2Y5MTljNzVkY2RlMWUzYzdmYzFjMDhmMjAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.94kbrDzTYlqiDHu2v8GtVGeGZKmiVEaoD1fe9N_6Rsk)

Hi Stefano, thanks for reaching out :) This error is different than what this issue is referring to. Did the machine/environment you were running the code have an internet connection?
The error you encountered happens when siibra cannot connect to any repositories to fetch the configuration. The [main](https://github.com/FZJ-INM1-BDA/siibra-configurations) is running normally and the [mirror](https://gitlab.ebrains.eu/ri/tech-hub/apps/siibra/siibra-configurations-mirror) is running at read-only so one of them should work except when there are network distruptions.
If you are still getting the error with a stable internet, could you please run:
```python
import siibra
siibra.cache.clear()
```
And then exit the session to try the code snippet you were running before?

**Comment by stefanonard85** [comment]
> > Hi @AhmetNSimsek ,
> > I am Stefano Nardone from BROAD Institute / HMS. I was attempting to use Siibra package in python but I have encountered the following error , see screenshot attached. Will the server of the mirror be restored soon ? and, if not, is there any possible solution to work with the package?
> > Thanks in advance for your help and availability. I wish you a good day.
> > Kind regards, Stefano nardone, PhD ![Capture](https://private-user-images.githubusercontent.com/16965990/385232315-89621c6a-1d82-423a-b6cf-40ca7e97f605.PNG?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzE0MDYzMTksIm5iZiI6MTczMTQwNjAxOSwicGF0aCI6Ii8xNjk2NTk5MC8zODUyMzIzMTUtODk2MjFjNmEtMWQ4Mi00MjNhLWI2Y2YtNDBjYTdlOTdmNjA1LlBORz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTEyVDEwMDY1OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTNkZTFlNThmNjUzOWI4ZTU0OGMwZTUzOWRlYjFjOTllYjVjYmM4M2Y5MTljNzVkY2RlMWUzYzdmYzFjMDhmMjAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.94kbrDzTYlqiDHu2v8GtVGeGZKmiVEaoD1fe9N_6Rsk)
> 
> Hi Stefano, thanks for reaching out :) This error is different than what this issue is referring to. Did the machine/environment you were running the code have an internet connection? The error you encountered happens when siibra cannot connect to any repositories to fetch the configuration. The [main](https://github.com/FZJ-INM1-BDA/siibra-configurations) is running normally and the [mirror](https://gitlab.ebrains.eu/ri/tech-hub/apps/siibra/siibra-configurations-mirror) is running at read-only so one of them should work except when there are network distruptions. If you are still getting the error with a stable internet, could you please run:
> 
> ```python
> import siibra
> siibra.cache.clear()
> ```
> 
> And then exit the session to try the code snippet you were running before?

Hi @AhmetNSimsek , all is working fine I just had to restart python. 
I really appreciated your help and thx a lot for your prompt answer .
I wish u a nice day :)

**Comment by AhmetNSimsek** [comment]
The mirror is back on again and mirror ci is reenabled.
