### ISSUE TITLE
[bug?] does not fetch some receptor data

### ISSUE THREAD

**Issue by xgui3783** [FZJ-INM1-BDA/siibra-python#69]
e.g. https://search.kg.ebrains.eu/instances/Dataset/33af3a71-4bd9-4ac6-9570-95769c8e1e49 seems to not be fetched (or the region parsed properly)

**Comment by dickscheid** [comment]
This is a new dataset which seems not to correspond to the previously used data structure. The fingerprint file is `..._fp.tsv`, whilst in other datasets of that project the fingerprints were `..._fp_<datestamp>.tsv`. This also caused the example notebook for retrieving multimodal data to fail. I will push a fix now.

**Comment by dickscheid** [comment]
Fixed in e47e12ab25

@xgui3783 can you try and confirm?
