### ISSUE TITLE
Provide autocompletion for parcellations and spaces linked to an atlas

### ISSUE THREAD

**Issue by marcenko** [FZJ-INM1-BDA/siibra-python#7]
When selectin parcellations and spaces from an atlas object, the `atlas.spaces` and `atlas.parcellations` members should behave like the main `brainscapes.spaces` and `brainscapes.parcellations` glossaries, in that they allow autocompltion and need not be used with list indices.

**Comment by dickscheid** [comment]
This has been introduced with GH-82 for `atlas.parcellations`, which is now a registry just like `siibra.parcellations` but with a reduced set of entries. Introduced for `atlas.spaces` in #d59e10a.
