### ISSUE TITLE
Default cache directory 

### ISSUE THREAD

**Issue by i-Zaak** [FZJ-INM1-BDA/siibra-python#80]
It would be useful if siibra tried to recover from non-writeable cache directory e.g. by using `tempfile.mkdtemp` similarly to how matplotlib handles the same situation: 

https://github.com/matplotlib/matplotlib/blob/c328fbce6128472d445d2f4dae12bb55d44b5db1/lib/matplotlib/__init__.py#L482

It would streamline the notebooks in the EBRAINS lab.

**Comment by dickscheid** [comment]
Thanks for reporting this, we will check the exact behaviour in the latest version and implement as you suggest.

**Comment by dickscheid** [comment]
Implemented in 64e12e86
