### ISSUE TITLE
check mirror of the predefined configurations

### ISSUE THREAD

**Issue by marcenko** [FZJ-INM1-BDA/siibra-python#84]
We are running a mirror of the predefined configurations, which is accessed if the main configuration repo is not reachable. Since v0.2 introduced breaking changes to the configurations, it is important that the mirror has the latest changes. 

We need to check wether the mirroring of configurations is working.

**Comment by dickscheid** [comment]
@marcenko @xgui3783 has this been checked meanwhile? Is the mirror up to date?

**Comment by xgui3783** [comment]
added ci script (that should run on every push to master/tag creation), which pushes tag/master to mirror

see pipeline run: https://jugit.fz-juelich.de/t.dickscheid/brainscapes-configurations/-/pipelines/49697

**Comment by xgui3783** [comment]
CI seems to have been fixed: https://jugit.fz-juelich.de/t.dickscheid/brainscapes-configurations/-/pipelines

leave in review for a few more releases, then mark as done
