### ISSUE TITLE
[feature request] allow region object to be easily associated with parcellation map

### ISSUE THREAD

**Issue by xgui3783** [FZJ-INM1-BDA/siibra-python#94]
Currently, there is no easy way to associate a region (e.g. `hoc1 left` with the corresponding parcellation map, given a space (e.g. `precomputed://https://neuroglancer.humanbrainproject.eu/precomputed/data-repo-ng-bot/20210714-julichbrain_v290_correctaffine/hbp-d000007_julichbrain-cytoatlas_dev/MPMs/29.0/GapMapPublicMPMAtlas_l_N10_nlin2StdColin27_29_publicDOI_7f7bae194464eb71431c9916614d5f89.nii.gz`

Whilst native methods exist, and potentially `mapIndex` can be used, it ideally can be done in less error prone, json encodable way.

**Comment by dickscheid** [comment]
To understand this better, what you want is: given a region name and a parcellation name and a space name, return the link to neuroglancer source plus labelindex?

**Comment by xgui3783** [comment]
Yes

**Comment by dickscheid** [comment]
So, one wayy I think this  could be done is as follows:

```python
def get_ngvolume_and_index(region, space):
    volumes = [
        v for v in region.parcellation.volumes
        if isinstance(v, siibra.volumes.NeuroglancerVolume)
        and v.space.matches(space) ]
    if len(volumes)<=region.index.map:
        return None
    else:
        return volumes[region.index.map].url, region.index.label
```

This could be used as e.g.

```python
atlas = siibra.atlases['human']
get_ngvolume_and_index(atlas.get_region('v1 left'), 'mni152')
```

which yields
```
('https://neuroglancer.humanbrainproject.eu/precomputed/data-repo-ng-bot/20210616-julichbrain-v2.9.0-complete-mpm/precomputed/GapMapPublicMPMAtlas_l_N10_nlin2StdICBM152asym2009c_29_publicDOI_77fea6ffe6f914b6d98fe88e85ff5b1b',
 8)
```

Is this what you'd like to get? We could create a member function of Parcellation along those lines, and expose it in the Atlas class as well.

**Comment by xgui3783** [comment]
I think I could implement this on frontend for now.

That's why I was asking about map index.

**Comment by dickscheid** [comment]
I think it is cheap but we can profile it. If you run it for all N regions in a parcellation we can probably do it more efficiently. For example,  we should not disambiguiate the space definition N times but rather provide a Space object from the beginning.

**Comment by dickscheid** [comment]
@xgui3783 shall we close this issue, or would you suggest to include this in the Python client?

**Comment by xgui3783** [comment]
```python
def get_ngvolume_and_index(region, space):
    volumes = [
        v for v in region.parcellation.volumes
        if isinstance(v, siibra.volumes.NeuroglancerVolume)
        and v.space.matches(space) ]
    if len(volumes)<=region.index.map:
        return None
    else:
        return volumes[region.index.map].url, region.index.label
```

currently fails with `hoc1` no hemisphere if we add a guard (return None when `region.index.map == None` ), it does not correctly return for big brain

(which should return `(https://neuroglancer.humanbrainproject.eu/precomputed/BigBrainRelease.2015/2019_05_01_v1, 1)` )

**Comment by xgui3783** [comment]
this issue is no longer relevant since the 0.4 rewrite.

The issue can be obtained the following way:

```python
import siibra
p29 = siibra.parcellations['2.9']
hoc1left = p29.get_region("hoc1 left")
_map = siibra.get_map(p29, "mni152", "labelled")

assert hoc1left.name in _map._indices
map_indices = _map._indices[hoc1left.name]
assert len(map_indices) == 1
map_index, = map_indices
vol = _map.volumes[map_index or 0]
ngsrc = vol["neuroglancer/precomputed"]

if map_index.fragment:
  return_val = ( ngsrc[vol.fragment], map_index.label )
else:
    return_val = ( ngsrc, map_index.label )


```
