### ISSUE TITLE
[bug] julich v29 does not support fsaverage

### ISSUE THREAD

**Issue by xgui3783** [FZJ-INM1-BDA/siibra-python#98]
## siibra version

as of v0.2a51 (commit 5143f40a20b5d66f91ee26ef9afb3b2779ed4c40)

## how to reproduce:

```python
import siibra
atlas=siibra.atlases['human']
fsaverage=atlas.spaces['fsaverage']
julich290=atlas.parcellations['julich 2 9']
julich290.supports_space(fsaverage) # expects True, actual return False
```

it does show the following warning message:

```sh
[siibra:INFO] A GiftiSurfaceLabeling object was registered, but this type is not yet explicitly supported.
```

## Why is this an issue?

`siibra-api` uses the `supports` call to populate `availableParcellations` key, which is in turn used by siibra-explorer to relate template spaces with parcellations. 

should julich v29 not support fsaverage, siibra-explorer will not be able to show julich v29 in fsaverage

## other

possibly related to #13

**Comment by dickscheid** [comment]
The problem is in core/concept.py:

```python
    @property
    def supported_spaces(self):
        """
        The list of spaces for which volumetric datasets are registered.
        """
        return list({v.space for v in self.volumes})
```

**Comment by AhmetNSimsek** [comment]
At the time of cec273e17547ab0bb10bb12e12c9406e5961a9ff, this is no longer an issue.
