### ISSUE TITLE
[bug] when siibra.atlases[spec] returns multiple results, crashes

### ISSUE THREAD

**Issue by xgui3783** [FZJ-INM1-BDA/siibra-python#99]
as of 906f5db3ac9886b0bffd557e19725d61d0ce6d8a

how to reproduce:

using `master` tag (or commit hash 1e7f0ff00dc2453f8a75707b96ff780c8b8a83d1) for siibra-configuration:

```python
import siibra
atlas=siibra.atlases['human']
```

expected: get human atlas
actual: 

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/xiao/dev/projects/siibra-python/siibra/commons.py", line 134, in __getitem__
    S = sorted(matches, reverse=True)
TypeError: '<' not supported between instances of 'Atlas' and 'Atlas'
```

likely, since monkey atlas === `Non-human primate atlas`, `atlases['human']`  now returns two results, and sorting them result in the error.

**Comment by dickscheid** [comment]
Should be resolved already by ad45d233bff4733a2b76ea15ff39116297669718
